# Generated by Django 5.2.7 on 2026-02-28 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('razao_social', models.CharField(max_length=255)),
                ('palavras_chave', models.JSONField(blank=True, default=list)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_fjl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"liccita"."empresa_perfil"',
                'unique_together': {('utilizador', 'cnpj')},
            },
        ),
        migrations.CreateModel(
            name='EmpresaCNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnaes', to='liccita.empresaperfil')),
            ],
            options={
                'db_table': '"liccita"."empresa_cnae"',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
