# Generated by Django 5.2.7 on 2026-03-08 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liccita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.IntegerField(help_text='Código numérico usado pela API da fonte.', unique=True)),
            ],
            options={
                'verbose_name': 'Modalidade de Licitação',
                'verbose_name_plural': 'Modalidades de Licitação',
                'db_table': '"liccita"."modalidade"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FonteLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=1000)),
                ('tipo', models.CharField(choices=[('api', 'API'), ('rss', 'RSS'), ('html', 'HTML'), ('js', 'JavaScript')], max_length=20)),
                ('formato', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('html', 'HTML')], max_length=10)),
                ('rate_limit', models.IntegerField(default=0)),
                ('auth', models.CharField(blank=True, max_length=100, null=True)),
                ('termos_uso', models.TextField(blank=True, null=True)),
                ('campos_disponiveis', models.JSONField(blank=True, null=True)),
                ('frequencia_atualizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('contrato_comercial', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('modalidades_a_coletar', models.ManyToManyField(blank=True, to='liccita.modalidade')),
            ],
            options={
                'verbose_name': 'Fonte de Licitação',
                'verbose_name_plural': 'Fontes de Licitação',
                'db_table': '"liccita"."fonte_licitacao"',
            },
        ),
        migrations.CreateModel(
            name='ModalidadeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=255, unique=True)),
                ('modalidade_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='liccita.modalidade')),
            ],
            options={
                'verbose_name': 'Sinônimo de Modalidade',
                'verbose_name_plural': 'Sinônimos de Modalidade',
                'db_table': '"liccita"."modalidade_alias"',
            },
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('titulo', models.TextField()),
                ('orgao', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_processo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_publicacao', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_abertura', models.DateTimeField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('edital_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('local_cidade', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('local_uf', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('modo_disputa', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('srp', models.BooleanField(blank=True, null=True)),
                ('modalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacoes', to='liccita.modalidade')),
            ],
            options={
                'verbose_name_plural': 'Licitações',
                'db_table': '"liccita"."licitacao"',
                'indexes': [models.Index(fields=['source'], name='licitacao_source_4e689f_idx'), models.Index(fields=['fingerprint'], name='licitacao_fingerp_d56cbe_idx'), models.Index(fields=['data_publicacao'], name='licitacao_data_pu_0d593e_idx')],
            },
        ),
    ]
