# Generated by Django 5.2.7 on 2026-03-08 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liccita', '0002_modalidade_fontelicitacao_modalidadealias_licitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='editais_salvos', to=settings.AUTH_USER_MODEL),
        ),
    ]
