# Generated by Django 5.2.7 on 2026-03-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liccita', '0003_licitacao_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='resumo_ia_mestre',
            field=models.TextField(blank=True, null=True, verbose_name='Super Resumo de Cache (IA)'),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='texto_pdf_extraido',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Extraído do PDF'),
        ),
    ]
