# Generated by Django 5.2.7 on 2026-03-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liccita', '0006_remove_licitacao_resumo_ia_mestre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertaLicitacao',
        ),
    ]
