# Generated by Django 5.2.7 on 2026-03-15 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liccita', '0007_delete_alertalicitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Licitações de Software', max_length=100)),
                ('palavras_chave', models.TextField(help_text='Ex: sistema, desenvolvimento, portal')),
                ('ufs', models.CharField(blank=True, help_text='Ex: SP, MG, DF (vazio = Brasil todo)', max_length=100, null=True)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frequencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal')], default='diaria', max_length=20)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"liccita"."alerta_licitacao"',
            },
        ),
    ]
