# Generated by Django 5.2.7 on 2026-03-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liccita', '0008_alertalicitacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaioXPersonalizado',
        ),
    ]
