# Generated by Django 5.2.7 on 2026-03-15 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liccita', '0009_delete_raioxpersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaioXPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio_markdown', models.TextField(verbose_name='Relatório da IA')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raiox_gerados', to='liccita.licitacao')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"liccita"."raiox_personalizado"',
                'unique_together': {('licitacao', 'utilizador')},
            },
        ),
    ]
