# Generated by Django 5.2.7 on 2026-03-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liccita', '0010_raioxpersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertalicitacao',
            name='palavras_chave',
        ),
        migrations.AddField(
            model_name='alertalicitacao',
            name='apenas_alto_match',
            field=models.BooleanField(default=False, help_text='Se True, a IA fará uma curadoria e enviará apenas editais com +80% de chance de vitória.'),
        ),
        migrations.CreateModel(
            name='EditalEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liccita.licitacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"liccita"."edital_enviado"',
                'unique_together': {('usuario', 'licitacao')},
            },
        ),
    ]
