# Generated by Django 5.2.7 on 2026-02-28 23:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('desconto_percentual', models.IntegerField(default=0, help_text='Ex: 50 para metade do preço', verbose_name='Desconto (%)')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('limite_creditos_ia', models.IntegerField(default=0, help_text='Quantos Raio-X a IA pode fazer por mês')),
                ('limite_cnaes', models.IntegerField(default=3)),
                ('limite_cnpjs', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Endereço de E-mail')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF ou CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telemóvel')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID no Gateway de Pagamento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado'), ('pendente', 'Pagamento Pendente')], default='pendente', max_length=20)),
                ('creditos_ia_disponiveis', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_renovacao', models.DateTimeField(blank=True, null=True)),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Assinatura no Gateway')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('cartao', 'Cartão de Crédito'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=50, null=True)),
                ('is_cortesia', models.BooleanField(default=False, help_text='Se marcado, o sistema não exige pagamento e mantém a conta ativa.', verbose_name='Conta VIP / Cortesia')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
                ('cupom', models.ForeignKey(blank=True, help_text='Cupom utilizado nesta assinatura', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cupomdesconto')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.plano')),
            ],
        ),
        migrations.AddField(
            model_name='plano',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='accounts.produto'),
        ),
    ]
