# Generated by Django 5.2.7 on 2026-03-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='ciclo',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10),
        ),
        migrations.AddField(
            model_name='plano',
            name='preco_anual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_invoice_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID da Fatura no Gateway')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor final já com descontos', max_digits=10, verbose_name='Valor Cobrado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('link_pagamento', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Checkout/Boleto')),
                ('link_nota_fiscal', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da NF-e')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='accounts.assinatura')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
