# Generated by Django 5.2.7 on 2026-03-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_assinatura_ciclo_plano_preco_anual_fatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['ordem', 'preco_mensal']},
        ),
        migrations.AddField(
            model_name='plano',
            name='cta',
            field=models.CharField(default='Assinar Agora', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='É o plano recomendado?'),
        ),
        migrations.AddField(
            model_name='plano',
            name='ordem',
            field=models.IntegerField(default=0, help_text='0 para o primeiro da esquerda, 1 para o do meio, etc.', verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='plano',
            name='recursos',
            field=models.JSONField(blank=True, default=list, verbose_name='Lista de Recursos'),
        ),
    ]
